import { defineConfig, devices } from '@playwright/test';

/**
 * Playwright configuration — E2E scaffold
 *
 * Generated by spec-kit e2e-scaffold template.
 * Adapt ports, URLs, and webServer commands to your project.
 *
 * Prerequisites:
 * 1. npm install -D @playwright/test @axe-core/playwright
 * 2. npx playwright install chromium
 * 3. Dev server running on [FRONTEND_PORT]
 *
 * See https://playwright.dev/docs/test-configuration
 */

export default defineConfig({
  testDir: './tests',
  testMatch: /.*\.spec\.ts$/,

  /* Maximum time per test */
  timeout: 90_000,

  /* Parallel execution (serial on CI for stability) */
  fullyParallel: true,
  workers: process.env.CI ? 1 : undefined,

  /* Fail the build on CI if test.only left in source */
  forbidOnly: !!process.env.CI,

  /* Retry on CI only */
  retries: process.env.CI ? 2 : 0,

  /* Reporters: HTML + JSON + console list */
  reporter: [
    ['html', { outputFolder: 'playwright-report', open: 'never' }],
    ['json', { outputFile: 'playwright-results.json' }],
    ['list'],
  ],

  use: {
    /* Base URL — adapt to your dev server */
    baseURL: 'http://localhost:[FRONTEND_PORT]',

    /* Trace on first retry for debugging */
    trace: 'on-first-retry',

    /* Capture screenshots and video only on failure */
    screenshot: 'only-on-failure',
    video: 'retain-on-failure',

    /* Visual regression snapshot path */
    snapshotPathTemplate: '{testDir}/__screenshots__/{testFilePath}/{arg}{ext}',

    /* Action and navigation timeouts */
    actionTimeout: 15_000,
    navigationTimeout: 20_000,

    headless: true,
  },

  /* Visual regression tolerance */
  expect: {
    toHaveScreenshot: {
      maxDiffPixels: 100,
      threshold: 0.2,
    },
  },

  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'] },
    },
    // Uncomment after >90% pass rate on Chromium
    // {
    //   name: 'firefox',
    //   use: { ...devices['Desktop Firefox'] },
    // },
    // {
    //   name: 'webkit',
    //   use: { ...devices['Desktop Safari'] },
    // },
  ],

  /* Dev server auto-launch — adapt commands and ports */
  webServer: [
    // Backend (if applicable)
    // {
    //   command: 'npm run dev',
    //   cwd: '../backend',
    //   url: 'http://localhost:[BACKEND_PORT]/health',
    //   reuseExistingServer: !process.env.CI,
    //   timeout: 120_000,
    //   stdout: 'pipe',
    //   stderr: 'pipe',
    // },
    {
      command: 'npm run dev',
      url: 'http://localhost:[FRONTEND_PORT]',
      reuseExistingServer: !process.env.CI,
      timeout: 120_000,
      stdout: 'pipe',
      stderr: 'pipe',
    },
  ],
});
